import { SourceSeedCompany } from '../../interfaces/job-source.interface';

export const GREENHOUSE_SEED_COMPANIES: SourceSeedCompany[] = [
    // ─── NON-PROFIT, NGO & GLOBAL DEVELOPMENT ─────────────────────────────────
    { companyName: 'One Acre Fund', boardToken: 'oneacrefund', websiteUrl: 'https://oneacrefund.org', targetRegions: ['Africa'] },
    { companyName: 'GiveDirectly', boardToken: 'givedirectly', websiteUrl: 'https://givedirectly.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Clinton Health Access Initiative (CHAI)', boardToken: 'chai', websiteUrl: 'https://clintonhealthaccess.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Mercy Corps', boardToken: 'mercycorps', websiteUrl: 'https://mercycorps.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'International Rescue Committee', boardToken: 'theirc', websiteUrl: 'https://rescue.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'TechnoServe', boardToken: 'technoserve', websiteUrl: 'https://technoserve.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Teach For All', boardToken: 'teachforall', websiteUrl: 'https://teachforall.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'World Resources Institute', boardToken: 'wri', websiteUrl: 'https://wri.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'PATH', boardToken: 'path', websiteUrl: 'https://path.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Evidence Action', boardToken: 'evidenceaction', websiteUrl: 'https://evidenceaction.org', targetRegions: ['Africa'] },
    { companyName: 'Bridge International Academies', boardToken: 'bridgeinternationalacademies', websiteUrl: 'https://bridgeinternationalacademies.com', targetRegions: ['Africa'] },
    { companyName: 'Living Goods', boardToken: 'livinggoods', websiteUrl: 'https://livinggoods.org', targetRegions: ['Africa'] },
    { companyName: 'Action Against Hunger', boardToken: 'actionagainsthunger', websiteUrl: 'https://actionagainsthunger.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Root Capital', boardToken: 'rootcapital', websiteUrl: 'https://rootcapital.org', targetRegions: ['Africa', 'US'] },
    { companyName: 'Global Citizen', boardToken: 'globalcitizen', websiteUrl: 'https://globalcitizen.org', targetRegions: ['Africa', 'US'] },

    // ─── HEALTHCARE, CLINICAL & LIFE SCIENCES ──────────────────────────────────
    { companyName: 'Zipline', boardToken: 'flyzipline', websiteUrl: 'https://flyzipline.com', targetRegions: ['Africa', 'US'] },
    { companyName: 'Cityblock Health', boardToken: 'cityblock', websiteUrl: 'https://cityblock.com', targetRegions: ['US'] },
    { companyName: 'Oak Street Health', boardToken: 'oakstreethealth', websiteUrl: 'https://oakstreethealth.com', targetRegions: ['US'] },
    { companyName: 'Ro', boardToken: 'ro', websiteUrl: 'https://ro.co', targetRegions: ['US'] },
    { companyName: 'DispatchHealth', boardToken: 'dispatchhealth', websiteUrl: 'https://dispatchhealth.com', targetRegions: ['US'] },
    { companyName: 'Omada Health', boardToken: 'omadahealth', websiteUrl: 'https://omadahealth.com', targetRegions: ['US'] },
    { companyName: 'Color Health', boardToken: 'color', websiteUrl: 'https://color.com', targetRegions: ['US'] },
    { companyName: 'Carbon Health', boardToken: 'carbonhealth', websiteUrl: 'https://carbonhealth.com', targetRegions: ['US'] },
    { companyName: 'Modern Animal', boardToken: 'modernanimal', websiteUrl: 'https://modernanimal.com', targetRegions: ['US'] },
    { companyName: 'Hims & Hers', boardToken: 'hims', websiteUrl: 'https://hims.com', targetRegions: ['US'] },
    { companyName: 'Grand Rounds Health', boardToken: 'grandroundshealth', websiteUrl: 'https://includedhealth.com', targetRegions: ['US'] },
    { companyName: 'Helix', boardToken: 'helix', websiteUrl: 'https://helix.com', targetRegions: ['US'] },
    { companyName: 'Maven Clinic', boardToken: 'mavenclinic', websiteUrl: 'https://mavenclinic.com', targetRegions: ['US'] },
    { companyName: 'Kallyope', boardToken: 'kallyope', websiteUrl: 'https://kallyope.com', targetRegions: ['US'] },
    { companyName: 'Treeline Biosciences', boardToken: 'treelinebio', websiteUrl: 'https://treeline.bio', targetRegions: ['US'] },

    // ─── AGRICULTURE, CLEAN ENERGY & SUSTAINABILITY ───────────────────────────
    { companyName: 'Sun King', boardToken: 'sunking', websiteUrl: 'https://sunking.com', targetRegions: ['Africa', 'US'] },
    { companyName: 'd.light', boardToken: 'dlight', websiteUrl: 'https://dlight.com', targetRegions: ['Africa', 'US'] },
    { companyName: 'Apollo Agriculture', boardToken: 'apolloagriculture', websiteUrl: 'https://apolloagriculture.com', targetRegions: ['Africa'] },
    { companyName: 'Form Energy', boardToken: 'formenergy', websiteUrl: 'https://formenergy.com', targetRegions: ['US'] },
    { companyName: 'Pivot Bio', boardToken: 'pivotbio', websiteUrl: 'https://pivotbio.com', targetRegions: ['US'] },
    { companyName: 'Indigo Ag', boardToken: 'indigoag', websiteUrl: 'https://indigoag.com', targetRegions: ['US'] },
    { companyName: 'Bowery Farming', boardToken: 'boweryfarming', websiteUrl: 'https://bowery.co', targetRegions: ['US'] },
    { companyName: 'Bboxx', boardToken: 'bboxx', websiteUrl: 'https://bboxx.com', targetRegions: ['Africa'] },
    { companyName: 'Twiga Foods', boardToken: 'twigafoods', websiteUrl: 'https://twiga.com', targetRegions: ['Africa'] },
    { companyName: 'Copia Global', boardToken: 'copiaglobal', websiteUrl: 'https://copia.co.ke', targetRegions: ['Africa'] },
    { companyName: 'Daystar Power', boardToken: 'daystarpower', websiteUrl: 'https://daystar-power.com', targetRegions: ['Africa'] },
    { companyName: 'Solar Sister', boardToken: 'solarsister', websiteUrl: 'https://solarsister.org', targetRegions: ['Africa'] },
    { companyName: 'Ampersand Solar E-Mobility', boardToken: 'ampersand', websiteUrl: 'https://ampersand.solar', targetRegions: ['Africa'] },

    // ─── FINANCE, BANKING & FINTECH ───────────────────────────────────────────
    { companyName: 'Moniepoint', boardToken: 'moniepoint', websiteUrl: 'https://moniepoint.com', targetRegions: ['Africa'] },
    { companyName: 'Kuda Bank', boardToken: 'kuda', websiteUrl: 'https://kuda.com', targetRegions: ['Africa'] },
    { companyName: 'Wave Mobile Money', boardToken: 'wave', websiteUrl: 'https://wave.com', targetRegions: ['Africa', 'US'] },
    { companyName: 'Chipper Cash', boardToken: 'chippercash', websiteUrl: 'https://chippercash.com', targetRegions: ['Africa', 'US'] },
    { companyName: 'Tala', boardToken: 'tala', websiteUrl: 'https://tala.co', targetRegions: ['Africa', 'US'] },
    { companyName: 'Branch International', boardToken: 'branch', websiteUrl: 'https://branch.co', targetRegions: ['Africa', 'US'] },
    { companyName: 'Stripe', boardToken: 'stripe', websiteUrl: 'https://stripe.com', targetRegions: ['US'] },
    { companyName: 'Affirm', boardToken: 'affirm', websiteUrl: 'https://affirm.com', targetRegions: ['US'] },
    { companyName: 'Chime', boardToken: 'chime', websiteUrl: 'https://chime.com', targetRegions: ['US'] },
    { companyName: 'Brex', boardToken: 'brex', websiteUrl: 'https://brex.com', targetRegions: ['US'] },
    { companyName: 'Gusto', boardToken: 'gusto', websiteUrl: 'https://gusto.com', targetRegions: ['US'] },
    { companyName: 'Robinhood', boardToken: 'robinhood', websiteUrl: 'https://robinhood.com', targetRegions: ['US'] },
    { companyName: 'Coinbase', boardToken: 'coinbase', websiteUrl: 'https://coinbase.com', targetRegions: ['US'] },
    { companyName: 'Remitly', boardToken: 'remitly', websiteUrl: 'https://remitly.com', targetRegions: ['US'] },
    { companyName: 'Lemonade', boardToken: 'lemonade', websiteUrl: 'https://lemonade.com', targetRegions: ['US'] },
    { companyName: 'Plaid', boardToken: 'plaid', websiteUrl: 'https://plaid.com', targetRegions: ['US'] },

    // ─── SUPPLY CHAIN, OPERATIONS & LOGISTICS ──────────────────────────────────
    { companyName: 'Flexport', boardToken: 'flexport', websiteUrl: 'https://flexport.com', targetRegions: ['US'] },
    { companyName: 'Instacart', boardToken: 'instacart', websiteUrl: 'https://instacart.com', targetRegions: ['US'] },
    { companyName: 'DoorDash', boardToken: 'doordash', websiteUrl: 'https://doordash.com', targetRegions: ['US'] },
    { companyName: 'Uber', boardToken: 'uber', websiteUrl: 'https://uber.com', targetRegions: ['US', 'Africa'] },
    { companyName: 'Lyft', boardToken: 'lyft', websiteUrl: 'https://lyft.com', targetRegions: ['US'] },
    { companyName: 'Kobo360', boardToken: 'kobo360', websiteUrl: 'https://kobo360.com', targetRegions: ['Africa'] },
    { companyName: 'Sendy', boardToken: 'sendy', websiteUrl: 'https://sendyit.com', targetRegions: ['Africa'] },
    { companyName: 'Samsara', boardToken: 'samsara', websiteUrl: 'https://samsara.com', targetRegions: ['US'] },
    { companyName: 'ShipBob', boardToken: 'shipbob', websiteUrl: 'https://shipbob.com', targetRegions: ['US'] },

    // ─── EDUCATION & EDTECH ───────────────────────────────────────────────────
    { companyName: 'NewGlobe Education', boardToken: 'newglobe', websiteUrl: 'https://newglobe.education', targetRegions: ['Africa', 'US'] },
    { companyName: 'Coursera', boardToken: 'coursera', websiteUrl: 'https://coursera.org', targetRegions: ['US'] },
    { companyName: 'Duolingo', boardToken: 'duolingo', websiteUrl: 'https://duolingo.com', targetRegions: ['US'] },
    { companyName: 'Chegg', boardToken: 'chegg', websiteUrl: 'https://chegg.com', targetRegions: ['US'] },
    { companyName: 'Guild Education', boardToken: 'guildeducation', websiteUrl: 'https://guild.com', targetRegions: ['US'] },
    { companyName: 'Outschool', boardToken: 'outschool', websiteUrl: 'https://outschool.com', targetRegions: ['US'] },
    { companyName: 'Udacity', boardToken: 'udacity', websiteUrl: 'https://udacity.com', targetRegions: ['US'] },
    { companyName: 'African Leadership Academy (ALA)', boardToken: 'africanleadershipacademy', websiteUrl: 'https://africanleadershipacademy.org', targetRegions: ['Africa'] },

    // ─── TECHNOLOGY, DESIGN & CLOUD ───────────────────────────────────────────
    { companyName: 'Figma', boardToken: 'figma', websiteUrl: 'https://figma.com', targetRegions: ['US'] },
    { companyName: 'Airbnb', boardToken: 'airbnb', websiteUrl: 'https://airbnb.com', targetRegions: ['US'] },
    { companyName: 'GitLab', boardToken: 'gitlab', websiteUrl: 'https://gitlab.com', targetRegions: ['US', 'Africa'] },
    { companyName: 'Datadog', boardToken: 'datadog', websiteUrl: 'https://datadog.com', targetRegions: ['US'] },
    { companyName: 'Twilio', boardToken: 'twilio', websiteUrl: 'https://twilio.com', targetRegions: ['US'] },
    { companyName: 'Dropbox', boardToken: 'dropbox', websiteUrl: 'https://dropbox.com', targetRegions: ['US'] },
    { companyName: 'Box', boardToken: 'box', websiteUrl: 'https://box.com', targetRegions: ['US'] },
    { companyName: 'Reddit', boardToken: 'reddit', websiteUrl: 'https://reddit.com', targetRegions: ['US'] },
    { companyName: 'Pinterest', boardToken: 'pinterest', websiteUrl: 'https://pinterest.com', targetRegions: ['US'] },
    { companyName: 'Discord', boardToken: 'discord', websiteUrl: 'https://discord.com', targetRegions: ['US'] },
    { companyName: 'Zoom', boardToken: 'zoom', websiteUrl: 'https://zoom.us', targetRegions: ['US'] },
    { companyName: 'Notion', boardToken: 'notion', websiteUrl: 'https://notion.so', targetRegions: ['US'] },
    { companyName: 'Canva', boardToken: 'canva', websiteUrl: 'https://canva.com', targetRegions: ['US'] },
    { companyName: 'Webflow', boardToken: 'webflow', websiteUrl: 'https://webflow.com', targetRegions: ['US'] },
    { companyName: 'Asana', boardToken: 'asana', websiteUrl: 'https://asana.com', targetRegions: ['US'] },
    { companyName: 'Zapier', boardToken: 'zapier', websiteUrl: 'https://zapier.com', targetRegions: ['US'] }
];
